CREATE SCHEMA IF NOT EXISTS ICAISA;
drop table ICAISA.MV_ISA_LOCALITE if exists;
drop table ICAISA.MV_ISA_PAYS if exists;
drop sequence if exists hibernate_sequence;
create table ICAISA.MV_ISA_LOCALITE (I_LIEU_ISA integer not null, C_CANTON varchar(255), I_PAYS integer, X_LOCALITE_F varchar(255), N_ORDRE_PTT integer, N_NPA integer, primary key (I_LIEU_ISA));
create table ICAISA.MV_ISA_PAYS (I_PAYS integer not null, C_PAYS varchar(255), C_ISO_PAYS varchar(255), B_VALIDE integer, X_PAYS_A varchar(255), X_PAYS_F varchar(255), primary key (I_PAYS));
create sequence hibernate_sequence start with 1 increment by 1;

SET foreign_key_checks = 0;

TRUNCATE TABLE ICAISA.MV_ISA_PAYS;
INSERT INTO ICAISA.MV_ISA_PAYS (I_PAYS, B_VALIDE, C_PAYS, C_ISO_PAYS, X_PAYS_F, X_PAYS_A) VALUES(1, 1, 'CH', 'CH', 'Suisse', 'Switzerland');
INSERT INTO ICAISA.MV_ISA_PAYS (I_PAYS, B_VALIDE, C_PAYS, C_ISO_PAYS, X_PAYS_F, X_PAYS_A) VALUES(2, 1, 'FR', 'FR', 'France', 'France');
INSERT INTO ICAISA.MV_ISA_PAYS (I_PAYS, B_VALIDE, C_PAYS, C_ISO_PAYS, X_PAYS_F, X_PAYS_A) VALUES(3, 1, 'SE', 'SE', 'Suède', 'Sweden');

TRUNCATE TABLE ICAISA.MV_ISA_LOCALITE;
INSERT INTO ICAISA.MV_ISA_LOCALITE (I_LIEU_ISA, N_ORDRE_PTT, I_PAYS, N_NPA, X_LOCALITE_F, C_CANTON) VALUES(1, 163, 1, 1015, 'Lausanne', 'VD');
INSERT INTO ICAISA.MV_ISA_LOCALITE (I_LIEU_ISA, N_ORDRE_PTT, I_PAYS, N_NPA, X_LOCALITE_F, C_CANTON) VALUES(2, 1681, 1, 3000, 'Bern', 'BE');
INSERT INTO ICAISA.MV_ISA_LOCALITE (I_LIEU_ISA, N_ORDRE_PTT, I_PAYS, N_NPA, X_LOCALITE_F, C_CANTON) VALUES(3, 164, 1, 1201, 'Genève 01', 'GE');
INSERT INTO ICAISA.MV_ISA_LOCALITE (I_LIEU_ISA, N_ORDRE_PTT, I_PAYS, N_NPA, X_LOCALITE_F, C_CANTON) VALUES(4, 165, 1, 1202, 'Genève 02', 'GE');
